import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="../assets/favicon.ico" sizes="any" />
      </head>
      <body className={inter.className}>
        <div className="sm:px-4 md:px-12 lg:px-18 xl:px-24 font-plus-jakarta-sans min-h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
